### ISSUE TITLE
Console output colors

### ISSUE THREAD

**Issue by niquedegraaff** [EHLOVader/laravel-elixir-livereload#11]
Please, when using colors in console, especially background colors make sure you changed the oposite (in this case, foreground) colors too. Because this is pain in my eye ;)

![Screenshot of pain in my eye](http://i.imgur.com/a6NIsVU.png)

Changed logger.js line 21 to

```
console.log(
    heading //gutil.colors.black(gutil.colors.bgGreen(heading))
);
```

![Screenshot of rest in my eye](http://i.imgur.com/Wlotzel.png)

**Comment by EHLOVader** [comment]
My package is not responsible for the colors you are complaining about. It
simply wraps the gulp-livereload package with sensible defaults for laravel
from elixir.

Also the most egregious color output there appears to be from sass, not
live reload.

**Comment by EHLOVader** [comment]
Yeah definitely not mine. Your second screenshot never made it through (something with Github's camo proxy.) 

You might note that the change you made is not in a file within this package, meaning you can't submit a PR for it, meaning this is the wrong place to be posting an issue. 

Very sorry about your eyes. :rage4:

**Comment by EHLOVader** [comment]
Also @Nique since you seem to be having a hard time finding the right place (saw you were in gulp-sass also) I wanted to help.

You will find that logger.js in laravel-elixir, however your problem isn't with any of these. They work correctly and your fix in fact breaks the intended operations. 

Here is the output you should expect to see from the laravel-elixir logger. 

![log output](https://i.imgur.com/dDgsZWl.png)
_sigh_ Camo is still failing me. https://i.imgur.com/dDgsZWl.png 

Anyway, the problem you see, is duplicated by running using the gulp task runner in phpstorm.

https://i.imgur.com/9zA8xxk.png

Appears to be specific to phpstorm and will have to be resolved by their team.

Good luck.

**Comment by niquedegraaff** [comment]
Yea I noticed they have to fix the phpstorm console for Windows 10 anyway. It simply doesn't work unless in legacy mode, Sorry for blaming the wrong guy. And my fix was just temporary to get around :).
