### ISSUE TITLE
Remove config.production check

### ISSUE THREAD

**Issue by mattzuba** [EHLOVader/laravel-elixir-livereload#2]
I don't think this is really needed, or perhaps turn it into a separate option.  I can't fathom anyone running watch or livereload in a production environment anyway, but it's throwing me off because I run elixir locally as if it was in production mode, so it minimizes my files in my public folder.  This isn't done on deployments, but part of commits.

**Comment by EHLOVader** [comment]
I am sure it isn't needed. I threw this together and I think this is an artifact from my attempts at preventing calls to `watch` from `default` and elsewhere.

I agree it shouldn't be run from production which is why it was put in there. However I am still getting issues with livereload running from the `default` action. I believe it is a limitation of Elixir.

**Comment by EHLOVader** [comment]
Updated in the old Elixir 2.x and not used in the new rewrite for 3.x so closing this for now.
