### ISSUE TITLE
laravel-elixir dependency in package.json

### ISSUE THREAD

**Issue by jadjoubran** [EHLOVader/laravel-elixir-livereload#8]
Is it really needed?

You can still do `require('laravel-elixir')` because laravel-elixir is already included in the main package.json

The problem here is that laravel-elixir already has huge dependencies

**Comment by EHLOVader** [comment]
Yes, it is needed. 
The version `1.x` of this module will only work with `laravel-elixir` `3.x` while the version `0.x` of this will only work with `laravel-elixir` `2.x`

I included it in the dependencies so it can be pinned to the specific versions of each to avoid any conflicts or problems should someone unknowingly try to upgrade either, or add this to their project with the wrong version. 

> The problem here is that laravel-elixir already has huge dependencies

What do you mean? What huge dependencies are you talking about that makes this a problem for you?

**Comment by jadjoubran** [comment]
hmm okay..

I meant that laravel-elixir already depends on 35 node modules that I have to re-download (that's around 100mb) and the internet is usually very slow in my area

**Comment by EHLOVader** [comment]
It shouldn't be downloading a second time. It also should be cached otherwise.

What is your version requirement for this and for `larave-elixir` in your project's package.json?
What version of NPM are you using?

It sounds like you are just starting a project, but if you aren't and you are having troubles perhaps you can try deleting the `node_modules` folder and reinstalling.

**Comment by EHLOVader** [comment]
Have found a way around this, think I will be updating this tonight with different kind of dependency. So it won't be as problematic.

**Comment by EHLOVader** [comment]
@jadjoubran empty your `node_modules` directory and try reinstalling with the latest version from a clean start. I have updated the module to use peer dependencies instead so that it should only check that it has the right version of `larvel-elixir` installed not install it itself.

Let me know how that works.

**Comment by jadjoubran** [comment]
That's great thanks! Here's where I'm using it [laravel5-angular-material-starter](https://github.com/jadjoubran/laravel5-angular-material-starter)

and yeah peer dependency makes much more sense
Thanks!
